### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by hellojaccc** [floe/backscrub#103]
I tried building on arch, with #93's manual. This error occured. How can i fix this?

```
[ 58%] Linking C static library libXNNPACK.a
[ 87%] Built target XNNPACK
make: *** [Makefile:156: all] Error 2
```

**Comment by floe** [comment]
I guess you'll have to build with `VERBOSE=1 make` and post the actual error before we can make any guess here.

**Comment by hellojaccc** [comment]
Sorry, i think i missed one step in #93 . It now has build correctly.

I have this error now though :(
```
ERROR: Could not open 'models/segm_full_v679.tflite'.
error: unable to load model from file: 'models/segm_full_v679.tflite'.
Error: Could not create mask context
```

**Comment by hellojaccc** [comment]
#101, Manually loading model works
