### ISSUE TITLE
OBS v4l2 plugin can't see the loopback camera device

### ISSUE THREAD

**Issue by ali1234** [floe/backscrub#105]
When selecting a v4l2 input device, only my real cameras are listed.

This is not a permissions problem - that would also prevent the gstreamer plugin from working. The virtual camera also has no problems working with mpv or web browsers, skype etc.

This can be worked around within OBS by using the gstreamer plugin instead of v4l2. Then use a pipeline like this:

    v4l2src device=/dev/video10 ! video.

I realise you probably can't fix this but I think it would be helpful to add the workaround to the documentation.

**Comment by phlash** [comment]
Thanks! Looks like this is a result of how the OBS v4l2 plugin finds inputs:
https://github.com/obsproject/obs-studio/blob/7ae6f328a1784954b96abcb8d4247207251192df/plugins/linux-v4l2/v4l2-input.c#L337
in particular it enumerates `/sys/class/video4linux` which only contains physical devices. Worth reporting as a bug to OBS?

**Comment by phlash** [comment]
So, I've tried this myself, and OBS _only lists inputs with a valid video stream_ at the time it is started. If I have `backscrub` running, then I can select my virtual camera and it all just works. If I _don't_ have `backscrub` running, then I only get the option of physical camera.

**Comment by ali1234** [comment]
I tried starting backscrub before OBS and it did not make any difference. It is still not listed in the list of inputs. I am using 27.0.1.

**Comment by phlash** [comment]
OK, reopening this as something is different :question:

**Comment by phlash** [comment]
Righto - I'm running OBS 26.1.2 (stock Debian 11 / stable), here's what I have configured and see:

 * v4l2 configuration:
 ```bash
  (/etc/modules-load.d/v4l2loopback)
v4l2loopback
 ```
 ```bash
 (/etc/modprobe.d/v4l2loopback-options)
 options v4l2loopback video_nr=10,11 exclusive_caps=1 card_label="Virtual Camera,Test Loopback"
 ```
```bash
% backscrub -c /dev/video0

**Comment by phlash** [comment]
Test repeated using OBS Studio 27.0.1-dfsg1-1 (from Debian bookworm / testing), and everything still works as above.

**Comment by ali1234** [comment]
This is likely to be caused by the snap container then.

**Comment by phlash** [comment]
I think so, thanks for raising the issue with snapcrafters, are we ok to close this here (possibly with a note in the docs and link to this ticket?)

**Comment by BenBE** [comment]
@phlash Once somebody™ added the note in the docs I'm fine with closing this.

**Comment by phlash** [comment]
docs updated in [README.md](/floe/backscrub/blob/main/README.md)
