### ISSUE TITLE
The sides of the image are cut off

### ISSUE THREAD

**Issue by ali1234** [floe/backscrub#106]
I built and ran the software according to the instruction in the README and this is what happened:

![image](https://user-images.githubusercontent.com/651970/131228190-ff5df334-492f-4713-b2e0-971dd6a770a3.png)

**Comment by phlash** [comment]
Yep, this is a result of the aspect ratio of the detection model in use. We have suggestions in #33 and #65 to fix this and are also keeping a watchful eye on new Tensorflow models that have a better ration for non-phone cameras..
