### ISSUE TITLE
Question about a line 

### ISSUE THREAD

**Issue by JVpltr** [floe/backscrub#110]
Hi, 
I have some question concerning this line :

out[n] = (val & 0xE0) | (out[n] >> 3);

I know what it does bitwise, but why 0xE0, what is it suppose to do in general ? out[n] in (out[n] >>3) is suppose to be the ofinal of the precedent frame ? 
 
I don't understand the meaning of this line, could someone help please ? 

Have a good day

**Comment by BenBE** [comment]
That line is used to have some decaying mask filter to improve temporal stability of the output. The idea is to weight in the previous few images (3) in the mask processing such that if there was mask recently it is still kept for a few more frames. This works around glitches in most of the segmentation networks that are temporally unstable.

**Comment by JVpltr** [comment]
Thanks a lot !
