### ISSUE TITLE
Calculation of model ratio seems to be wrong.

### ISSUE THREAD

**Issue by progandy** [floe/backscrub#118]
As far as I understand, ```ctx.input.cols``` is the width of the model input, ```ctx.input.rows``` its height.
The ratio is set as
https://github.com/floe/backscrub/blob/36083432c723eb0bc3f2d427fa9335a152a33111/lib/libbackscrub.cc#L226
Then the ROI width is calculated as ```height/ctx.ratio```.
https://github.com/floe/backscrub/blob/36083432c723eb0bc3f2d427fa9335a152a33111/lib/libbackscrub.cc#L229

```height/ctx.ratio``` results in ```height/ctx.input.cols/ctx.input.rows```.
This seems wrong to me, the ratio needs be be inverted to
```ctx.ratio = ctx.input.rows/ctx.input.cols```

That is the result you get when equating the ratios and solving for the width:
(assuming number of cols is a width, number of rows is a height)
```
   width / height = ctx.input.cols / ctx.input.rows
=> width = (ctx.input.cols/ctx.input.rows) * height
=> width = height * (input.cols / input.rows)
=> width = height / (1 / (input.cols / input.rows) )
=> width = height / (input.rows / input.cols )
```

The inverted ratio seems to be correct for all places where the ratio is used.

That fix helps with the landscape version of the mlkit / mediapipe model (published under Apache 2.0):
https://google.github.io/mediapipe/solutions/models.html#selfie-segmentation

By the way, the meet model seems to be a landscape model as well according to the input tensor metadata contrary to the information on the model card?

Edit: Only changing the ratio will cause a crash with a camera that is only providing a 4:3 image (e.g. 640x480) and no 16:9 image like 1280x720.

**Comment by phlash** [comment]
Thanks @progandy, I suspect that code is a result of the original deeplab model (which is square) and assuming that height will always be the constraining factor, probably better to calculate both ratios (height and width), and choose whichever is lower to scale up to the source size: https://stackoverflow.com/questions/1106339/resize-image-to-fit-in-bounding-box before centring on the other axis.
