### ISSUE TITLE
How can I install Tensorflow Lite 2.5.0?

### ISSUE THREAD

**Issue by mozo78** [floe/backscrub#128]
Hello,
I can't fugure out how exactly to install Tensorflow Lite 2.5.0 from the repo for Ubuntu 20.04:
https://github.com/tensorflow/tensorflow/tree/v2.5.0/tensorflow/lite

Any help will be greatly appreciated!

**Comment by BenBE** [comment]
You mean for building this repository? Or from the packages in your distro?

**Comment by mozo78** [comment]
Ah, it seems it's included in the project, thanks :)
