### ISSUE TITLE
Background video support

### ISSUE THREAD

**Issue by valk** [floe/backscrub#131]
So guys, I wanted to have fun and added a [video support](https://github.com/valk/backscrub/commit/ce0d9b3c5152b16dd288d86fde9bfb4d32a68bac).
Thought it might be interesting to some of you. If you use my branch then the parameter for video is -z so you might have a bash script like this:

```
#!/bin/bash

cd /path/to/backscrub

read -p "Video?" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  ./build/backscrub -c /dev/video0 -v /dev/video10 -z /path/to/some.mp4
else
  ./build/backscrub -c /dev/video0 -v /dev/video10 -b /path/to/some.png -m models/selfiesegmentation_mlkit-256x256-2021_01_19-v1215.f16.tflite
fi
```

**Comment by BenBE** [comment]
With the latest merge a few days ago background video support has been merged in the main development branch as a working feature (after having been in experimental for a few months).
