### ISSUE TITLE
Build issue on ubuntu 21.10

### ISSUE THREAD

**Issue by doktorjw** [floe/backscrub#140]
I've just cloned the repository (used to use the deepbacksub one). On my prior version, I was able to build fine, but now ... following the direction, I get the following error:

```
[ 96%] Building CXX object tensorflow-lite/CMakeFiles/tensorflow-lite.dir/simple_memory_arena_debug_dump.cc.o
/home/dr_j/projects/backscrub/tensorflow/tensorflow/lite/simple_memory_arena_debug_dump.cc:27:43: error: ‘numeric_limits’ is not a member of ‘std’
   27 | constexpr int32_t kNodeNotAssigned = std::numeric_limits<int32_t>::max();
      |                                           ^~~~~~~~~~~~~~
/home/dr_j/projects/backscrub/tensorflow/tensorflow/lite/simple_memory_arena_debug_dump.cc:27:65: error: expected primary-expression before ‘>’ token
   27 | constexpr int32_t kNodeNotAssigned = std::numeric_limits<int32_t>::max();
      |                                                                 ^
/home/dr_j/projects/backscrub/tensorflow/tensorflow/lite/simple_memory_arena_debug_dump.cc:27:68: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   27 | constexpr int32_t kNodeNotAssigned = std::numeric_limits<int32_t>::max();
      |                                                                    ^~~
      |                                                                    std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /home/dr_j/projects/backscrub/tensorflow/tensorflow/lite/simple_memory_arena_debug_dump.cc:15:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make[2]: *** [tensorflow-lite/CMakeFiles/tensorflow-lite.dir/build.make:2357: tensorflow-lite/CMakeFiles/tensorflow-lite.dir/simple_memory_arena_debug_dump.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1436: tensorflow-lite/CMakeFiles/tensorflow-lite.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

Thoughts? Ideas?

Thx ---- john

**Comment by BenBE** [comment]
This looks like a build issue with the TensorFlow Lite version we're using.

You can try to `git checkout` a newer version of the submodule to see if the issue has been addressed upstream already. An alternative is to file a bug report with upstream TensorFlow directly. The repository can be found at https://github.com/tensorflow/tensorflow/

I haven't checkd building against `v2.8.0`, but chances are good that backscrub itself should build just fine, once the TFLite stuff builds properly.

**Comment by phlash** [comment]
You may also want to check you are at the expected/tested tag for Tensorflow:
```bash
% cd tensorflow
% git log
```
should show `tag: v2.7.0` tag at the top of the listing.

I have had compile failures when switching between Tensorflow tags without cleaning the build:
```bash
% cmake --build build -t clean
% cmake --build build
```
usually sorts things out.

Finally - we have seen failures with newer compilers than the Tensorflow team test/support - I note you are on Ubuntu 21.10 which may fit this category - Ubuntu 16.04 is the last tested version here: https://www.tensorflow.org/lite/guide/build_cmake. This is definitely worth checking the Tensorflow repo issues for...

**Comment by doktorjw** [comment]
How would I change the version of tensorflow that the build is relying on? I've tried a few things, but the build keeps wanting to update to v2.7.0.

**Comment by phlash** [comment]
You can override the TENSORFLOW variable, which inhibits the checkout in `CMakeLists.txt`:
```bash
% cmake -B build -DTENSORFLOW=tensorflow
% cd tensorflow
% git checkout v2.8.0
% cd ..
% cmake --build build
```
should say `-- Using specified Tensorflow: tensorflow` at the start of the log, and will no longer force checkout of v2.7.0

**Comment by doktorjw** [comment]
And .... we have success with those build instructions, and using tensorflow 2.8.0. So I won't bother filing a bug report with the tensorflow project.

Thx very much --- seems to be working just fine. I did have to restart my Teams call I was testing in, but .... the video is showing and up and looks pretty good.

**Comment by phlash** [comment]
Cool! Looks like an update to 2.8.0 for us would be useful for newer distros - I'll check on my Debian stable and PR as appropriate. Thanks for testing!
