### ISSUE TITLE
Initialization failure for strange image resolutions (like 1280x480)

### ISSUE THREAD

**Issue by jjsarton** [floe/backscrub#146]
If backscrub is only launched with one of the -w or -h argument, backscrub crash.
Please check that both parameter width and height are stated.

**Comment by BenBE** [comment]
Tracing the issue inside GDB points to some OpenCV internals:

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) ./modules/core/src/matrix.cpp:810: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'
```

The last operation attempted is in `calcmask.cc` on line 96 (branch experimental):
```c
		if(!bs_maskgen_process(maskctx, *frame_current, *mask_current)) {
```

Will need some further digging.

But initial investigation suggests that the fallback resolution used as default (`-w 640 -h 480`). Thus when using just `-w 1280` the attempted configuration is `-w 1280 -h 480`.

Attempting this resolution directly (with both parameters given) also fails for me.

**Comment by BenBE** [comment]
Further debugging hints at a problem with the aspect ratio of the target video stream. 320x480 doesn't work, 640x480 works, 848x480 works, but 856x480 does not … Neither do 400x480, 560x480, 632x480 work.

The crash is independent of the background image used.

**Comment by jjsarton** [comment]
I have performed some tests, and if I state the width and height correctly according to the sizes returned by v4l2-ctl --list-formats.ext  backscrub work as expected. If you check if any one the the -w or -h parameter is passed to backscrub and not both are given, you can issue an error message and exit.
It is also possible to check, at startup the camera capabilities and choose the proper height or width according to the width or height argument.

**Comment by jjsarton** [comment]
I have modified a little bit app/deepseg.c

After the "size_t blur_strength = 0;"  declaration within the main() I have added "int hw = 0;".
after:
```
        			if (!width) {
					showUsage = true;
				}
```
I added "hw |= 1;" and after the check for height: "hw |= 2;"
With this we have only to check if hw contain the value 0 (no -h -w arguments) or 3 (both parameter set).
At the end of the loop we can add:

`if ( hw && hw !=3 ) showUsage = true;`

With this we check if all needed parameters are given and if not so, print the usage and exit.

**Comment by BenBE** [comment]
The bug is not that the crash is caused by the missing arguments (that's fully intentonial by defaulting to the values posted above), but the initialization of certain aspect rations causing an assertion failure when creating the necessary memory. And that issue can still be triggered by providing crazy dimensions like 1920x240 on the command line. Thus your change might fix symptoms, but it doesn't address the cause.

**Comment by jjsarton** [comment]
I have made a little test for all resolutions supported by a logitec C922, I had no failure,
If I set a wrong width and or height
```
	cap.set(cv::CAP_PROP_FRAME_WIDTH,  width);
	cap.set(cv::CAP_PROP_FRAME_HEIGHT, height);
```
the function will set anythings accepted by the webcam for example 1280x800 will probably allocate for 1280x720 which is a resolution supported by the webcam.
So you can probably set the given width and heigth allocated by:
``` 
	// default green screen background
	cv::Mat bg = cv::Mat(height, width, CV_8UC3, cv::Scalar(0, 255, 0));
```
after setting of the camera parameters

**Comment by jjsarton** [comment]
I removed the lines
```
	// default green screen background
	cv::Mat bg = cv::Mat(height, width, CV_8UC3, cv::Scalar(0, 255, 0));
```
After the lines:
```
	cap.set(cv::CAP_PROP_FRAME_WIDTH,  width);	
	cap.set(cv::CAP_PROP_FRAME_HEIGHT, height);
```
I added:

```
	width=cap.get(cv::CAP_PROP_FRAME_WIDTH);
	height=	cap.get(cv::CAP_PROP_FRAME_HEIGHT);
	// default green screen background
       cv::Mat bg = cv::Mat(height, width, CV_8UC3, cv::Scalar(0, 255, 0));
```
With this backscrub work well.
The  choosed resolution is what i want, if I pass correct width and height
If one of the parameter is wrong, opencv seem to choose a resolution near the passed dimensions.

**Comment by phlash** [comment]
Thanks for digging in on this @jjsarton, your last suggested fix seems sensible, as it reflects the actual input stream resolution back to the rest of the application. Are you happy to submit a PR for this?

**Comment by BenBE** [comment]
Does it reflect the resolution and respect the provided user argument? i.e. User says `-w 1000`, camera stream opens with 800x600. Will it:

* Force 800 x 600
* Resize to 1000x750 to keep aspect ratio of stream?

I'd prefer the second behaviour (with minimal cropping if necessary).

**Comment by phlash** [comment]
Hmmn, good point - rule of least surprise should apply - perhaps that's stopping when the requested resolution isn't possible?

**Comment by jjsarton** [comment]
As far I have seen on different camera, the aspect ratio will not always be respected. This seems to be dependent of the resolution table returned by the camera. 
Force 800x600 will not work with all cams. 
## Formats according v4l2-ctl on 3 Notebooks

V4l2-ctl --list-formats-ext -d /dev/videoX return the following:

| i5     | i7     | i9     | Aspect |
|:------:|:------:|:------:|:------:|
|1280x720|1280x720|1280x720|16:9    |
|960x540 |        |960x540 |16:9    |
|848x480 |        |848x480 |16:9    |
|640x480 |640x480 |640x480 | 4:3    |
|640x360 |640x360 |640x360 |16:9    |
|424x240 |        |        |16:9    |
|320x240 |        |        | 4:3    |
|320x180 |        |        |16:9    |

A solution will be to take a higher resolution ant to resize/crop the result in a further step.

**Comment by BenBE** [comment]
Or have `-cw`/`-ch` for the camera width/height, which defaults to the output width/height given in `-w`/`-h`?

**Comment by jjsarton** [comment]
This is a possiblity.
In the mean time i have a new crash, I inspect why:
```
backscrub  -c /dev/video3 -v /dev/video0 -w 2034 -h 1536 -b ~/DSC03478.JPG  -d -d
```
work!
```
backscrub  -c /dev/video3 -v /dev/video0 -w 2034 -h 1536 -b ~/DSC03478.JPG  -f MJPG -d -d
```
with:

matrix.cpp:810: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

The requested size is okay for the Logitech C922 cam but only present if the cam stream YUV2!
This mean probably that setting MJPG shall be tested before setting the background parameters!

**Comment by jjsarton** [comment]
If we move the call:
```
	if (fourcc)
		cap.set(cv::CAP_PROP_FOURCC, fourcc);
```
before:
```
      cap.set(cv::CAP_PROP_FRAME_WIDTH,  width);
```
there is no crash, of course we will get, with the c922 cam only the size 1280x720

**Comment by BenBE** [comment]
IIRC there was an issue with some cams requiring the FOURCC to be set in order to provide their larger resolutions.

**Comment by jjsarton** [comment]
Right, the larger resolution is bigger with the compressed format MJPG. The limitation is due to the hardware.
For example, my USB camera C922 is attached via USB and the max size is primary limited by the USB bandwidth. On the other hand, the cam hardware may not be fast enough to compress very big video and the higher resolution with compression is not available
YUV2: 2304x1296 and 2304x1536 are stated, with MJPG the max size is 1920x1080.
If the user want very big resolution, it can only get that what the camera provides. It is difficult to catch all possible settings and take the decision, very low FPS or higher.
If we make sure that backscrub don't crash and deliver results, possibly not fully as wanted, wse have the better way. This must be documented.

[oftoppic]
I have tried the body-pix model and get crash. Do it work for you?
I suspect that the ROI calculation is not okay, the tensor size is 257x257
[/offtopic]

**Comment by phlash** [comment]
OK folks - I'm going to make some suggestions here, based on the conversation so far - yea or nay please!:
1. Deprecate width/height switches in favour of geometry (WxH), this avoids confusion with internal defaults. Log deprecation if used.
2. Allow specification of seperate camera and output geometries: `[-cg <camera-geo>] [-og <output-geo>]`.
3. Deprecated `[-w] [-h]` switches set both camera & output, _then_ new switches can override.
4. Re-order camera startup as per @jjsarton fixes to avoid crashes (set format first, recover true geometry afterwards)
5. Default output geometry to true camera geometry, unless overridden.
6. Re-scale camera to output geometry at end of processing (part of writing to V4L2). To me this is less surprising than rescaling before processing..
7. Default camera geometry to 640x480, for compatibility with existing behavour and as a likely successful resolution.
8. Display final geometries on both log output and in monitor screen.

**Comment by jjsarton** [comment]
@phlash your suggestion are ok for me.
Do you mean 1280x720 or any other recognized values for [-cg <camera-geo>],  this seems for me to be much intuitive.

The default geometry for both camera **and** output (640x480) is probably the best choice in regard to WebRTC and low bandwidth, as well as CPU/GPU with poor performance.

**Comment by phlash** [comment]
> Do you mean 1280x720 or any other recognized values for [-cg ], this seems for me to be much intuitive.

Yes, that's the idea, a lot of other tools (such as ImageMagick, FFmpeg, etc.) use this geometry representation format.

Since the output geometry will be the true camera geometry unless otherwise specified, and the camera geometry defaults to 640x480 (likely to be available), then the output geometry will also be 640x480 if not specified.

**Comment by BenBE** [comment]
> OK folks - I'm going to make some suggestions here, based on the conversation so far - yea or nay please!:
> 
> 1. Deprecate `[-w] [-h]` switches in favour of geometry (`WxH`), this avoids confusion with internal defaults. Log deprecation if used.

Yay

> 2. Allow specification of separate camera and output geometries: `[-cg <camera-geo>] [-og <output-geo>]`.

Yay

> 3. Deprecated `[-w] [-h]` switches set camera geometry. `[-cg]` can override.

`-w`/`-h` should hard-conflict with the geometry settings of `--cg`/`--og`. Thus if `--cg`/`--og` given, no `-w`/`-h` is accepted; hard-error.

> 4. Re-order camera startup as per @jjsarton fixes to avoid crashes (set format first, recover true geometry afterwards)

Yay.

> 5. Default output geometry to true camera geometry, unless otherwise specified.

Yay.

> 6. Re-scale camera to output geometry at end of processing (when scaling mask up). To me this is less surprising than rescaling before processing.

Should keep aspect ratio if possible …

> 7. Default camera geometry to 640x480, for compatibility with existing behaviour and as a likely successful resolution.

Yay.

> 8. Display final geometries on both log output and in monitor screen.

Yay.

**Comment by phlash** [comment]
> -w/-h should hard-conflict with the geometry settings of --cg/--og. Thus if --cg/--og given, no -w/-h is accepted; hard-error.

Yep, that's sensible, if you know about / use the new stuff, then using the old stuff should barf to catch your typos.

**Comment by jjsarton** [comment]
I thing that we can do as follow:

| --cg            | --og            | -w/-h        | Action            |
|:---------------:|:---------------:|:------------:|:------------------|
| set             |                 |              | og=cg             |
|                 | set             |              | cg=og             |
| set             | set             |              | apply as required |
| set             |                 | set          | og=WxH            |
|                 | set             | set          | cg=Wxh            |
| set             | set             | set          | ignore WxH        |

**Comment by jjsarton** [comment]
The code may look as folow:
```
int size_param = 0;

// parse argument and modify size_param

if --cg set
   size_param |= 1

if  --og set
   size_para |= 2;

if -w -h set
   size_param |= 4;
 
// check an set other

switch(size_param)
case 0)
   cg=og=defaiult
case 1)
    og=cg
case 2)
    cg=og
case 3)
    ...
case 5)
   og=h/w
...
```

**Comment by phlash** [comment]
@jjsarton That was where I was going with the original suggestion, however I think it's better (less confusing, identifies typos in scripts etc.) to fail if both old/new switches are used on the same command line as suggested by @BenBE.

**Comment by jjsarton** [comment]
Failing is okay bur the error/warning messages shall be good enough for fixing the cause of error. 
We can add a parameter --check, which allows checking all parameters passed an ending backscrub after the checks are done.
With this we can also see if the --cg geometry and the geometry returned after initializing the camera are the same, ...

How to deal with input errors is always philosophical.

**Comment by BenBE** [comment]
I don't think the `--check` is needed for the behaviour as layed out by @phlash and me: If an inconsistent mix of arguments is specified, it will just fail (with a proper error message), if it needs to adjust what was given, it will warn and report what it actually had to resort to. The `--check` you proposed would in that case be more akin to a `--dry-run` feature; which should be handled as part of another PR IMHO.
