### ISSUE TITLE
Crash due to misplaced line

### ISSUE THREAD

**Issue by jjsarton** [floe/backscrub#152]
https://github.com/floe/backscrub/blob/4f70bc15fa467640504a2fce0e6553872c5435eb/app/deepseg.cc#L634
If the line is moved after the sanity check the crash which occur under some circumstance will not occur.

**Comment by BenBE** [comment]
Please create such suggestions as pull requests, as this allows to see them in the full context and makes overall handling of them easier.

This change looks good, but you will need to move both lines 634 and 635 after 637.
