### ISSUE TITLE
Mutex handling

### ISSUE THREAD

**Issue by jjsarton** [floe/backscrub#160]
If we use mutex the code shall look as folow

```
get mutex (..,hold(mutex))
do critical part
release mutex (hold.unlock())
```
Releasing the mutex was not done. Due to this, the total time between retrieving the frame and sending the constructed frame was around 33 ms while using rotating:earth.webm. For animated.gif the total time within the main loop was heavely changing.
Adding hold.unlock() after the critical part solved this.

You may have a look at my Testing branch in order to see my improvement and bug fixes. It will be nice to test my version.

**Comment by BenBE** [comment]
While the basic idea of releasing the lock early has some merits, doing so without using RAII in the code allows for some edge cases where the lock isn't properly freed. And just as it happens your very implementation contains places where releasing the lock is forgotten. Thus while it might be slower at times it's far less prone to errors to stick with RAII than to try getting the overall reference counting right. After all: Simply cleaning the strong reference once you're done with it suffices to achieve a similar effect and doesn't screw too much with trying to get all the reference counting right.

Besides: Your current implementation with +800-400 is quite far off from this repository, thus unless you extract a clean PR it will be hard to integrate anything regardless how well it is …
