### ISSUE TITLE
Name suggestions

### ISSUE THREAD

**Issue by jasonmf** [floe/backscrub#6]
- Backdrop
- Backscrub
- ViCK (Virtual Chroma Key)

**Comment by connornishijima** [comment]
RUB: Remover of Unwanted Backdrops

or

F-BATS: Future of Broke Ass Twitch Streamers?

**Comment by floe** [comment]
BaDASs: BackgrounD Ai SubStitution (as per https://hackaday.com/2020/04/10/background-substitution-no-green-screen-required/#comment-6236347)

**Comment by floe** [comment]
Backscrub is also nice, though :-D

**Comment by Dhar** [comment]
Backscratch
Backscratcher
BRUH - Background Remover Using Heuristics
SCRUB - Scrub Cleanly Removes Ugly/Unwanted Backgrounds

**Comment by ferman** [comment]
I like ViCK

- Vebcam - virtual webcam
- VirCK - play on ViCK making the virtual more obvious
- WebCKam - web chroma key cam

**Comment by cwharris** [comment]
I personally like “mugshot”, “yourface”, or “facemask”. 🤷🏻‍♂️

**Comment by hectormgerardo** [comment]
Maybe is too late to suggest. I was thinkin' on «CamBacks» as a short for Camera Backgrounds.

**Comment by floe** [comment]
Other suggestions (thanks everyone): 

- TinGS (TinGS is not a Green Screen) by @blackcoffeerider
- ViViBaRe (Virtual Video Background Removal) by @neato-nick

Problem is that this has now attracted a bit of attention under the original name. I know GitHub does forwards after renames, will have to try that, I guess.

**Comment by phlash** [comment]
Shall we have a vote on this, looks like suggestions have dried up?
:+1: for Backscrub from me..

**Comment by floe** [comment]
Backscrub is indeed the best one so far :-) anyone has experience with renaming repos? IIRC there will be forwards so it should work transparently?

**Comment by BenBE** [comment]
On the client side you can either simply rename it in your `.git/config` or use `git remote set-url REMOTE NEWURL` and `git remote set-url --push REMOTE NEWURL` accordingly. This aside you can simply rename it in the admin panel on Github. We may also consider putting the repo in an Github organization for better access management; you'd create the org and than transfer ownership to that org in the next step. This also makes it more obvious who has access to the repo.

**Comment by floe** [comment]
Just pulled the trigger and renamed it to "backscrub", let's hope all the forwards work as promised (looking good on my side so far).
