### ISSUE TITLE
Update experimental to latest tflite release

### ISSUE THREAD

**Issue by BenBE** [floe/backscrub#61]
There's some new upstream tflite release r2.5 we could update our submodule link for tflite to?
Or any particular reasons to keep it at the current (old, untagged) revision?

**Comment by floe** [comment]
The current submodule revision should correspond to 2.4.0, I think. But AFAICT there's no reason to stay at 2.4 if it also works with 2.5, haven't tested that yet, though.

**Comment by BenBE** [comment]
No time to test r2.5 here either.

I'd suggest to push this to experimental for now.

**Comment by phlash** [comment]
See also #84

**Comment by BenBE** [comment]
If TFlite 2.5 is officially released (didn't check right now), go ahead with 2.5. Shouldn't make much difference API-wise.

**Comment by floe** [comment]
If it's compatible (and I assume yes), then this could go directly into main IMHO.

**Comment by phlash** [comment]
Just tried this locally - works for me without issue against `experimental`
