### ISSUE TITLE
Split cam processing and video filtering

### ISSUE THREAD

**Issue by BenBE** [floe/backscrub#75]
To allow for re-using our tool as base for a plugin (like e.g. for OBS, cf. #2) we should see if we can split out the main filtering function in a way that can be re-used by other tools. `deepseg` in this scenario would mostly become "just a frontend" to that library.

similar approaches are e.g. `rrdtool`, which is basically a handy CLI wrapper for `librrd`; or `ffmpeg` that is a baroque collection of calls to `libavcodec`, `libavdevice`, `libavfilter`, `libavformat`, `libavresample`, `libavutil`, and others.

For `deepseg` we'd have a library that retrieves frames in it's input API and provides both a polling and callback interface for handling the processed segmentation mask. The main program itself just would handle providing input frames and handling the process to combine the background via the mask with the input frames.

Any plugin-capable program, like e.g. OBS, could then call the library to query for this mask and perform its own version of the processing. Parts of the post-processing may also be part of the library (like the light wrapping from #67, or non-static background-combination from video sources).

**Comment by BenBE** [comment]
Also note this remark from https://github.com/floe/deepbacksub/issues/10#issuecomment-825571701 for a rationale.

**Comment by phlash** [comment]
Closed in #86
