### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by SamSpiri** [floe/backscrub#79]
Is it possible to use NVIDIA CUDA acceleration?
In order to use body-pix or deeplab with 15+ FPS performance.

**Comment by phlash** [comment]
From the documentation here: https://www.tensorflow.org/lite/performance/delegates I don't think there is a Linux/x86 targetted GPU delegate that could be used, but happy to be proven wrong by someone!

Sticking to CPU, we may be able to improve by explicitly building the XNNPACK backend: https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html

**Comment by floe** [comment]
Oho, neat! The main reason for picking TFLite in the first place was that it has a workable CPU backend, "regular" Tensorflow basically requires a Nvidia GPU (at least as of ~ 1 year ago). And I guess part of the appeal of backscrub is that it doesn't require anything fancy in terms of hardware.

**Comment by phlash** [comment]
I have just discovered that there is an OpenCL delegate (https://github.com/tensorflow/tensorflow/tree/v2.4.1/tensorflow/lite/delegates/gpu), which can be built via CMake (only tested by Google on Android cross-builds but _should_ work on Linux), however it's fighting me at the moment courtesy of untested Linux headers, and _yet-another-flatbuffers-schema_ that needs compiling..

**Comment by SamSpiri** [comment]
XNNPACK results you've got are very promising!

I was looking through internet and found that tflite models are not so good for GPU acceleration.
It is much better in TF no the LITE version. But since the whole project is based on tflite it probably will take a lot of effort to refactor to TF. Or am I wrong?

**Comment by SamSpiri** [comment]
btw: https://github.com/mikan3rd/react-body-pix-sample

**Comment by phlash** [comment]
> I was looking through internet and found that tflite models are not so good for GPU acceleration.

Thanks for the feedback and research @SamSpiri. Given tflite is built for use on mobile devices and specifically for their GPUs I'm a little surprised you found tflite models are 'not so good for GPU' (perhaps it's that desktop GPUs might have support for 64bit floats, mobile tends not to?) - got any links to what you discovered please?

As @floe notes above, this project uses tflite so it can operate _without_ a GPU, and switching to full-fat Tensorflow will kill that off, so for now I think we're likely to stay with tflite. Code-wise, it wouldn't be particularly difficult/different to use full TF, and as/when we get a more pluggable structure I would expect someone to write the appropriate plugin :smile:

**Comment by phlash** [comment]
Hacked together GPU support now in my tree: https://github.com/phlash/backscrub/tree/xnnpack-test (yes, this is now a badly named branch!) Unable to test on my T430 as it does not support double precision (64bit) floats and crashes when loading any model :disappointed: If you wish to crash your own machine.. set `BACKSCRUB_GPU=yes` in your environment before running.

This branch _must_ be built with `cmake`, as there is no makefile support for GPU and XNNPACK in Tensorflow Lite tree.

I also discovered that adding in a custom build rule to compile flatbuffer schemas to headers magically also builds  the `flatc` compiler and uses it... CMake is a bit scary at times!

**Comment by SamSpiri** [comment]
That works just amazing! Even without GPU it works super quick with just 20% cpu usage on deeplab and body-pix.
But when run with GPU than CPU usage drops to 10% and GPU is barely used (only 80Mb ram and few % compute)
I'll share later my dockerfile and docker-compose to build and run the whole thing that I used.

**Comment by SamSpiri** [comment]
https://github.com/floe/backscrub/pull/81

**Comment by vongillus** [comment]
@phlash : I have tested your code with XNNPACK and it's simply amazing. With the selfie model I go from more than 200% CPU to around 100%. Very nice since my hardware an old iMac i7 2.93Ghz running Ubuntu cannot do GPU.

**Comment by phlash** [comment]
Now that we have CMake builds in, I'll get the XNNPACK stuff into main, so this should be default performance for everyone.

**Comment by vongillus** [comment]
As a side comment, it's also running on ARM Cortex 53 (Pinephone running Mobian) with around 5FPS with the selfie model and the gain with XNNPACK is nearly the same going down from 252% CPU to 185% CPU. I had though to compile with Tensorflow 2.5 since there is a bug in XNNPACK on version 2.4.1 which prevents compiling on ARM. So it would be nice to go towards that version if possible.

**Comment by BenBE** [comment]
> I had though to compile with Tensorflow 2.5 since there is a bug in XNNPACK on version 2.4.1 which prevents compiling on ARM. So it would be nice to go towards that version if possible.

Can you open up a new issue for this, so we have something to track this? As API of TF shouldn't change too much, this might be easily doable.

**Comment by phlash** [comment]
TF v2.5.0 now awaiting test in PR #88

**Comment by floe** [comment]
`main` branch builds nicely with TF 2.5 and XNNPACK, so this can be closed?
