### ISSUE TITLE
Tidy up C-isms towards C++17

### ISSUE THREAD

**Issue by phlash** [floe/backscrub#80]
The codebase has a fair amount of 'C-isms' such as `typedef` statements, `#include <C header>` instead of corresponding C++ headers, anachronistic use of `strcmp` and the like. This task is here to remind us to tidy up as we go...

**Comment by BenBE** [comment]
I'd argue to even go to C++17 at least. The difference between C++11 and C++17 doesn't seem to huge at first, but there are some things in it (especially for multi-processing/threading) that we definitively should use.

As you need a somewhat recent kernel for the `v4l2loopback` part anyways I think it's safe to assume, that systems that could potentially run that kernel module also bring a recent enough compiler to do C++17.

NB: I know some people that follow a policy of using the most recently published C++ standard starting at latest with the year after hit has been published/finalized. I think that's overshooting for this project, but by no means something that prohibits us from being more recent.

**Comment by phlash** [comment]
Agreed, I probably have the oldest tooling (G++ 8.3.0) which fully supports c++17 (https://gcc.gnu.org/projects/cxx-status.html)

**Comment by floe** [comment]
With the merge from experimental done, can this be closed?

**Comment by BenBE** [comment]
Let's do so for now and reopen concrete issues once there's more things we find for cleanup.
