### ISSUE TITLE
Upgrading to Tensorflow Lite 2.5

### ISSUE THREAD

**Issue by vongillus** [floe/backscrub#84]
Right now the backscrub code relies on TF Lite 2.4.1.

When I tested the new code of @Phlash with XNNPACK on ARM architecture (aarch64), there is a bug in the version of XNNPACK packaged with TF 2.4.1 which prevents compiling it:

https://github.com/google/XNNPACK/issues/987

On the latest version of TF Lite 2.5, I could compile backscrub fork with XNNPACK on ARM without issues.

**Comment by phlash** [comment]
I guess we need a few people to give this a go and report back if it's ok?

@vongillus are you happy to put a PR in for the version change, then testers can pull that PR down to test, I use these incantations:
```bash
%> git checkout main
%> git fetch origin pull/<PR number>/head:<local branch name>
%> git checkout <local branch name>
%> cmake --build build/
%> build/deepseg -d -d -c <your camera device> -v <your loopback device>
```

**Comment by phlash** [comment]
Looks good in #61, I'll also test against `main` and put in the PR if it works for me.
